name: Run DeepSeek Coder 1.3B with Bolt.DIY

on:
  workflow_dispatch:

jobs:
  ollama-bolt:
    runs-on: ubuntu-latest
    steps:
    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.ai/install.sh | sh

    - name: Pull DeepSeek Coder 1.3B
      run: |
        ollama rm deepseek-coder:1.3b -f || true
        ollama pull deepseek-coder:1.3b

    - name: Start Ollama
      run: |
        sudo ss -K dst localhost dport = 11434 || true
        OLLAMA_HOST=0.0.0.0 OLLAMA_ORIGINS=* ollama serve &
        timeout 180 bash -c 'until ollama list | grep -q "deepseek"; do sleep 10; done'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Clone Bolt.DIY Template
      run: |
        git clone https://github.com/stackblitz-labs/bolt.diy-template bolt-app
        cd bolt-app
        npm install
        
        # Add Ollama integration
        npm install axios
        sed -i '/import { Bolt }/a import axios from "axios";' src/app.js

    - name: Start Bolt.DIY Server
      run: |
        cd bolt-app
        npm run dev &
        timeout 30 bash -c 'until curl -s localhost:3000 >/dev/null; do sleep 2; done'

    - name: Install ngrok
      run: |
        wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar -xf ngrok-v3-stable-linux-amd64.tgz
        chmod +x ngrok

    - name: Expose UI
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
      run: |
        ./ngrok config add-authtoken $NGROK_TOKEN
        ./ngrok http 3000
