name: Run DeepSeek Coder with Bolt.DIY

on:
  workflow_dispatch:

jobs:
  ollama-bolt:
    runs-on: ubuntu-latest
    steps:
    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.ai/install.sh | sh

    - name: Pull DeepSeek Coder
      run: |
        ollama rm deepseek-coder:1.3b -f || true
        ollama pull deepseek-coder:1.3b

    - name: Start Ollama
      run: |
        sudo ss -K dst localhost dport = 11434 || true
        OLLAMA_HOST=0.0.0.0 ollama serve &
        timeout 180 bash -c 'until ollama list | grep -q "deepseek"; do sleep 5; done'

    - name: Clone Bolt.DIY
      run: |
        git clone https://github.com/Kidjig/bolt.diy.git bolt-app
        cd bolt-app

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install Dependencies
      run: |
        cd bolt-app
        npm install
        npm install axios

    - name: Add Ollama Integration
      run: |
        cd bolt-app
        mkdir -p src
        echo 'import axios from "axios";

        export async function ollamaGenerate(prompt) {
          try {
            const response = await axios.post("http://localhost:11434/api/generate", {
              model: "deepseek-coder:1.3b",
              prompt: prompt,
              stream: false
            });
            return response.data.response;
          } catch (error) {
            return `Error: ${error.message}`;
          }
        }' > src/ollama.js

        echo 'import { ollamaGenerate } from "./ollama.js";
        app.route("/api/generate", async (req) => {
          const result = await ollamaGenerate(req.body.prompt);
          return new Response(result);
        });' >> src/app.js

    - name: Start Server (Fixed)
      run: |
        cd bolt-app
        # Use correct port (5173) and suppress warnings
        nohup npm run dev > server.log 2>&1 &
        
        # Verify server startup with correct port
        timeout 60 bash -c 'until curl -s localhost:5173 >/dev/null; do sleep 2; done'
        cat server.log

    - name: Install and Configure ngrok
      run: |
        wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar -xf ngrok-v3-stable-linux-amd64.tgz
        chmod +x ngrok
        
        # Start ngrok after server confirmation
        ./ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
        ./ngrok http 5173 > ngrok.log &
        timeout 10 bash -c 'until grep -q "started tunnel" ngrok.log; do sleep 1; done'
        cat ngrok.log
        echo "Public URL: $(curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"
