name: Run Ollama Phi + Open WebUI

on:
  workflow_dispatch:

jobs:
  ollama-webui:
    runs-on: ubuntu-latest
    steps:
    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.ai/install.sh | sh

    - name: Pull Phi model
      run: ollama pull phi

    - name: Start Ollama (Fixed)
      run: |
        # Force release port 11434
        sudo ss -K dst localhost dport = 11434 || true
        
        # Start Ollama on all interfaces
        OLLAMA_HOST=0.0.0.0 ollama serve &
        
        # Wait for API readiness
        timeout 30 bash -c 'until curl -s http://localhost:11434 >/dev/null; do sleep 2; done'
        
        # Verify
        curl -v http://localhost:11434/api/tags

    - name: Install Docker
      run: |
        sudo apt-get remove -y docker docker-engine docker.io containerd runc
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl gnupg
        sudo install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu noble stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        sudo docker --version

    - name: Run Open WebUI
      run: |
        # Get host IP dynamically
        HOST_IP=$(hostname -I | awk '{print $1}')
        
        docker run -d -p 8080:8080 \
          -e OLLAMA_BASE_URL="http://$HOST_IP:11434" \
          -e DEFAULT_USERNAME="admin" \
          -e DEFAULT_PASSWORD="your_password" \
          -v open-webui:/app/backend/data \
          --name open-webui \
          ghcr.io/open-webui/open-webui:main

    # Debugging steps
    - name: Verify Network Connectivity
      run: |
        HOST_IP=$(hostname -I | awk '{print $1}')
        echo "Host IP: $HOST_IP"
        docker run --rm alpine ping -c 3 $HOST_IP

    - name: Test Ollama API from Container
      run: |
        HOST_IP=$(hostname -I | awk '{print $1}')
        docker run --rm curlimages/curl curl -v http://$HOST_IP:11434/api/tags

    - name: Check Open WebUI Logs
      run: docker logs open-webui

    - name: Install ngrok
      run: |
        wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar -xf ngrok-v3-stable-linux-amd64.tgz
        chmod +x ngrok

    - name: Expose Open WebUI via ngrok
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
      run: |
        ./ngrok config add-authtoken $NGROK_TOKEN
        ./ngrok http 8080
