name: Run Ollama Phi + Open WebUI

on:
  workflow_dispatch:

jobs:
  ollama-webui:
    runs-on: ubuntu-latest
    steps:
    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.ai/install.sh | sh

    - name: Pull Phi Model
      run: |
        ollama rm phi -f || true
        ollama pull phi

    - name: Start Ollama (Robust)
      run: |
        sudo ss -K dst localhost dport = 11434 || true
        OLLAMA_HOST=0.0.0.0 OLLAMA_ORIGINS=* ollama serve &
        
        # Wait for model availability
        timeout 120 bash -c 'until ollama list | grep -q phi; do sleep 5; done'
        curl -v http://localhost:11434/api/tags

    - name: Install Docker Properly
      run: |
        sudo apt-get remove -y docker docker-engine docker.io containerd runc
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl gnupg
        sudo install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu noble stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        sudo docker --version

    - name: Run Open WebUI (Host Network)
      run: |
        docker run -d --network host \
          -e OLLAMA_BASE_URL="http://localhost:11434" \
          -e WEBUI_SECRET_KEY="your_secret_key" \
          -e DEFAULT_USERNAME="admin" \
          -e DEFAULT_PASSWORD="your_secure_password" \
          -v open-webui:/app/backend/data \
          --name open-webui \
          ghcr.io/open-webui/open-webui:main

    - name: Verify Connections
      run: |
        # Verify Ollama from host
        curl -s http://localhost:11434/api/tags | jq
        
        # Verify from container
        docker exec open-webui curl -s http://localhost:11434/api/tags | jq

    - name: Install ngrok
      run: |
        wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar -xf ngrok-v3-stable-linux-amd64.tgz
        chmod +x ngrok

    - name: Expose WebUI
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
      run: |
        ./ngrok config add-authtoken $NGROK_TOKEN
        ./ngrok http 8080
